// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_Label7;
lv_obj_t * uic_Spinner1;
lv_obj_t * uic_connect;
lv_obj_t * ui_connect = NULL;
lv_obj_t * ui_Spinner1 = NULL;
lv_obj_t * ui_Label7 = NULL;
// event funtions

// build funtions

void ui_connect_screen_init(void)
{
    ui_connect = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_connect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_connect, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_connect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner1 = lv_spinner_create(ui_connect, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 129);
    lv_obj_set_height(ui_Spinner1, 131);
    lv_obj_set_x(ui_Spinner1, 1);
    lv_obj_set_y(ui_Spinner1, -79);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner1, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_connect);
    lv_obj_set_width(ui_Label7, 390);
    lv_obj_set_height(ui_Label7, 121);
    lv_obj_set_x(ui_Label7, -1);
    lv_obj_set_y(ui_Label7, 57);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "正在连接 Wi-Fi...");
    lv_obj_clear_flag(ui_Label7, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scroll_dir(ui_Label7, LV_DIR_LEFT);
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_cn_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_connect = ui_connect;
    uic_Spinner1 = ui_Spinner1;
    uic_Label7 = ui_Label7;

}

void ui_connect_screen_destroy(void)
{
    if(ui_connect) lv_obj_del(ui_connect);

    // NULL screen variables
    uic_connect = NULL;
    ui_connect = NULL;
    uic_Spinner1 = NULL;
    ui_Spinner1 = NULL;
    uic_Label7 = NULL;
    ui_Label7 = NULL;

}
