// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_CONNECT_H
#define UI_CONNECT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_connect
extern void ui_connect_screen_init(void);
extern void ui_connect_screen_destroy(void);
extern lv_obj_t * ui_connect;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Label7;
// CUSTOM VARIABLES
extern lv_obj_t * uic_connect;
extern lv_obj_t * uic_Spinner1;
extern lv_obj_t * uic_Label7;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

