// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_Label8;
lv_obj_t * uic_Label3;
lv_obj_t * uic_Label2;
lv_obj_t * uic_Label1;
lv_obj_t * uic_Label5;
lv_obj_t * uic_Label4;
lv_obj_t * uic_Panel1;
lv_obj_t * uic_Monitor;
lv_obj_t * ui_Monitor = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label8 = NULL;
// event funtions

// build funtions

void ui_Monitor_screen_init(void)
{
    ui_Monitor = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Monitor, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Panel1 = lv_obj_create(ui_Monitor);
    lv_obj_set_width(ui_Panel1, 418);
    lv_obj_set_height(ui_Panel1, 37);
    lv_obj_set_x(ui_Panel1, -3);
    lv_obj_set_y(ui_Panel1, -132);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Monitor);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 11);
    lv_obj_set_y(ui_Label4, 7);
    lv_label_set_text(ui_Label4, "-100dBm");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_cn_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Monitor);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -14);
    lv_obj_set_y(ui_Label5, 7);
    lv_obj_set_align(ui_Label5, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Label5, "12:00:00");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Monitor);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 162);
    lv_obj_set_y(ui_Label6, 7);
    lv_label_set_text(ui_Label6, "3.50 V");
    lv_obj_set_style_text_color(ui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Monitor);
    lv_obj_set_width(ui_Label1, 383);
    lv_obj_set_height(ui_Label1, 30);
    lv_obj_set_x(ui_Label1, 11);
    lv_obj_set_y(ui_Label1, 47);
    lv_label_set_text(ui_Label1, "");
    lv_obj_set_scroll_dir(ui_Label1, LV_DIR_LEFT);
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_cn_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Monitor);
    lv_obj_set_width(ui_Label2, 383);
    lv_obj_set_height(ui_Label2, 84);
    lv_obj_set_x(ui_Label2, 11);
    lv_obj_set_y(ui_Label2, 81);
    lv_label_set_text(ui_Label2, "\n\n");
    lv_obj_set_scroll_dir(ui_Label2, LV_DIR_LEFT);
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &ui_font_cn_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Monitor);
    lv_obj_set_width(ui_Panel3, 418);
    lv_obj_set_height(ui_Panel3, 23);
    lv_obj_set_x(ui_Panel3, -3);
    lv_obj_set_y(ui_Panel3, 36);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Monitor);
    lv_obj_set_width(ui_Label3, 283);
    lv_obj_set_height(ui_Label3, 21);
    lv_obj_set_x(ui_Label3, -51);
    lv_obj_set_y(ui_Label3, 37);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "44.1k   STEREO   MP3    120 kbps");
    lv_obj_clear_flag(ui_Label3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label3, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Monitor);
    lv_obj_set_width(ui_Label8, 91);
    lv_obj_set_height(ui_Label8, 19);
    lv_obj_set_x(ui_Label8, 148);
    lv_obj_set_y(ui_Label8, 36);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "---.- kbps");
    lv_obj_clear_flag(ui_Label8, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label8, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label8, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_Monitor = ui_Monitor;
    uic_Panel1 = ui_Panel1;
    uic_Label4 = ui_Label4;
    uic_Label5 = ui_Label5;
    uic_Label1 = ui_Label1;
    uic_Label2 = ui_Label2;
    uic_Label3 = ui_Label3;
    uic_Label8 = ui_Label8;

}

void ui_Monitor_screen_destroy(void)
{
    if(ui_Monitor) lv_obj_del(ui_Monitor);

    // NULL screen variables
    uic_Monitor = NULL;
    ui_Monitor = NULL;
    uic_Panel1 = NULL;
    ui_Panel1 = NULL;
    uic_Label4 = NULL;
    ui_Label4 = NULL;
    uic_Label5 = NULL;
    ui_Label5 = NULL;
    ui_Label6 = NULL;
    uic_Label1 = NULL;
    ui_Label1 = NULL;
    uic_Label2 = NULL;
    ui_Label2 = NULL;
    ui_Panel3 = NULL;
    uic_Label3 = NULL;
    ui_Label3 = NULL;
    uic_Label8 = NULL;
    ui_Label8 = NULL;

}
