// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MONITOR_H
#define UI_MONITOR_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Monitor
extern void ui_Monitor_screen_init(void);
extern void ui_Monitor_screen_destroy(void);
extern lv_obj_t * ui_Monitor;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label8;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Monitor;
extern lv_obj_t * uic_Panel1;
extern lv_obj_t * uic_Label4;
extern lv_obj_t * uic_Label5;
extern lv_obj_t * uic_Label1;
extern lv_obj_t * uic_Label2;
extern lv_obj_t * uic_Label3;
extern lv_obj_t * uic_Label8;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

